
## Check of the source file is there

find_file (HAVE_TEST_CFITSIO_CC TestCFITSIO.cc
  PATHS ${CMAKE_MODULE_PATH}
  )

if (HAVE_TEST_CFITSIO_CC)
  
  try_run(CFITSIO_RUN_RESULT_VAR CFITSIO_COMPILE_RESULT_VAR
    ${PROJECT_BINARY_DIR}
    ${HAVE_TEST_CFITSIO_CC}
    CMAKE_FLAGS -DLINK_LIBRARIES:STRING=${CFITSIO_LIBRARIES}
    COMPILE_DEFINITIONS -I${CFITSIO_INCLUDES}
    COMPILE_OUTPUT_VARIABLE CFITSIO_COMPILE_OUTPUT_VARIABLE
    RUN_OUTPUT_VARIABLE CFITSIO_RUN_OUTPUT_VARIABLE
    )
  
  if (CFITSIO_COMPILE_RESULT_VAR)
    if (CFITSIO_RUN_RESULT_VAR)

      ## Extract library version

      string(REGEX REPLACE "CFITSIO_VERSION ([0-9]+).*" "\\1" CFITSIO_VERSION ${CFITSIO_RUN_OUTPUT_VARIABLE})
      string(REGEX REPLACE ".*CFITSIO_MAJOR ([0-9]+).*" "\\1" CFITSIO_VERSION_MAJOR ${CFITSIO_RUN_OUTPUT_VARIABLE})
      string(REGEX REPLACE ".*CFITSIO_MINOR ([0-9]+).*" "\\1" CFITSIO_VERSION_MINOR ${CFITSIO_RUN_OUTPUT_VARIABLE})

      set (CFITSIO_VERSION ${CFITSIO_VERSION_MAJOR}.${CFITSIO_VERSION_MINOR})

      ## CFITSIO global variables

      string(REGEX REPLACE ".*NIOBUF ([0-9]+).*" "\\1" CFITSIO_NIOBUF ${CFITSIO_RUN_OUTPUT_VARIABLE})
      string(REGEX REPLACE ".*IOBUFLEN ([0-9]+).*" "\\1" CFITSIO_IOBUFLEN ${CFITSIO_RUN_OUTPUT_VARIABLE})
      string(REGEX REPLACE ".*FLEN_FILENAME ([0-9]+).*" "\\1" CFITSIO_FLEN_FILENAME ${CFITSIO_RUN_OUTPUT_VARIABLE})
      string(REGEX REPLACE ".*FLEN_KEYWORD ([0-9]+).*" "\\1" CFITSIO_FLEN_KEYWORD ${CFITSIO_RUN_OUTPUT_VARIABLE})

    else (CFITSIO_RUN_RESULT_VAR)
      message (STATUS "[CFITSIO] Failed to run TestCFITSIO")
    endif (CFITSIO_RUN_RESULT_VAR)
  else (CFITSIO_COMPILE_RESULT_VAR)
    message (STATUS "[CFITSIO] Failed to compile TestCFITSIO.cc")
  endif (CFITSIO_COMPILE_RESULT_VAR)
  
else (HAVE_TEST_CFITSIO_CC)
  
  message (STATUS "[CFITSIO] Failed to find test program TestCFITSIO.cc")

endif (HAVE_TEST_CFITSIO_CC)
